
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ReactNode } from "react";
import { StoreProvider } from "@/redux/StoreProvider";
import { Search } from "@/components/Search";

const inter = Inter({ subsets: ["latin", "cyrillic"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const runtime = "edge";

export default function RootLayout({ 
  children,
}: {
  children: ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <div className="w-3/4 mx-auto">
          <StoreProvider>
            <Search />
          </StoreProvider>
          {children}
        </div>
      </body>
    </html>
  );
}
